# Generated by Django 3.2.3 on 2021-07-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOG', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
