# Generated by Django 3.2.3 on 2021-07-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOG', '0002_auto_20210722_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ManyToManyField(blank=True, null=True, to='CATALOG.School'),
        ),
    ]
