# Generated by Django 3.2.3 on 2021-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOG', '0003_teacher_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='school',
            new_name='schools',
        ),
    ]
