# Generated by Django 3.2.3 on 2021-07-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOG', '0004_auto_20210723_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='schools',
            field=models.ManyToManyField(blank=True, to='CATALOG.School'),
        ),
    ]
