# Generated by Django 3.2.3 on 2021-07-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOG', '0005_alter_teacher_schools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
