# Generated by Django 3.2.3 on 2021-07-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOG', '0006_auto_20210724_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
    ]
