# Generated by Django 3.2.3 on 2021-07-24 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOG', '0007_remove_student_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='class',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentarchive',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentarchive',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 24, 12, 56, 33, 955605, tzinfo=utc)),
        ),
    ]
